### ISSUE TITLE
Feature request: `preload_association` at instance level

### ISSUE THREAD

**Issue by mdesantis** [makandra/edge_rider#2]
Hello,

I use a lot `preload_associations`, and it happens that I almost always use it on single records; so I find handly a `preload_associations` method at instance level, so you can do f.e. something like:

``` ruby
current_user.preload_associations player_profile: :player_roles
```

At the moment I'm using the following monkey patch:

``` ruby
module Tascout
  module MonkeyPatches
    # ActiveRecord::Base.preload_associations is defined by EdgeRider
    if defined? EdgeRider
      # Defines ActiveRecord::Base#preload_associations, which
      # preloads associations at instance level. Example:
      #
      #     user = User.first
      #
      #     # This loads user's player_roles
      #     user.preload_associations player_profile: :player_roles
      #
      #     # This will not query for user's player_roles
      #     user.player_profile.player_roles
      module PreloadAssociationsInstanceMethod
        def preload_associations(*args)
          self.class.preload_associations [self], *args
        end
      end

      ActiveRecord::Base.prepend PreloadAssociationsInstanceMethod
    end
  end
end
```

Let me know you are interested in adding this feature to EdgeRider.

**Comment by codener** [comment]
@triskweline it have been 4 years now.. isn't this working as described here? 

https://github.com/makandra/edge_rider/tree/d70de9848f336f1cb6b4352bfc1b3918dc0ae970#preload-associations-for-loaded-activerecords

**Comment by triskweline** [comment]
@mdesantis' idea was to expose this as an instance method (instead of a class method) to simplify the call for an individual record.
